# Generated by Django 3.1.7 on 2021-09-07 14:26

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import grifo_utils.paths.validators
import mywebsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMultimediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('file_upload', models.FileField(default='default/', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/Users/brunogrifo/Documents/bgrifo/aboutme/aboutme/mediafiles/'), upload_to=mywebsite.models.get_upload_path_pp, validators=[grifo_utils.paths.validators.FileValidator(content_types=('video/mp4', 'video/mpeg', 'video/quicktime', 'video/webm', 'video/x-ms-wmv', 'image/jpeg', 'image/jpg', 'image/png', 'image/gif'), max_size=20971520)])),
                ('file_thumb', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Conteúdo Multimédia',
                'verbose_name_plural': 'Conteúdos Multimédia',
                'db_table': 'db_ContentMultimediaFile',
            },
        ),
        migrations.CreateModel(
            name='ContentMultimediaFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_multimedia_file_type', models.CharField(max_length=100, verbose_name='Content Multimedia File Type')),
            ],
            options={
                'verbose_name': 'Content Multimedia File Type',
                'verbose_name_plural': 'Content Multimedia File Types',
                'db_table': 'db_ContentMultimediaFileType',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'db_Tag',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=3000)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mywebsite.contentmultimediafile')),
                ('tags', models.ManyToManyField(related_name='list_tags', to='mywebsite.Tag')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'db_Project',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=120, unique=True)),
                ('body', models.CharField(max_length=3000)),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mywebsite.contentmultimediafile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.project')),
            ],
            options={
                'verbose_name': 'Paragraph',
                'verbose_name_plural': 'Paragraphs',
                'db_table': 'db_Paragraph',
            },
        ),
        migrations.AddField(
            model_name='contentmultimediafile',
            name='content_multimedia_file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mywebsite.contentmultimediafiletype'),
        ),
    ]
