# Generated by Django 3.1.7 on 2021-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_auto_20210908_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='body',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
