# Generated by Django 3.1.7 on 2021-09-15 09:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_auto_20210908_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='#129CFF', max_length=18),
        ),
    ]
