# Generated by Django 3.1.7 on 2021-09-16 10:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_project_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('file_upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/brunogrifo/Documents/bgrifo/aboutme/aboutme/mediafiles/'), upload_to='')),
            ],
            options={
                'verbose_name': 'cv',
                'verbose_name_plural': 'cv',
                'db_table': 'db_cv',
            },
        ),
    ]
